// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 临时硬编码（仅用于调试，生产环境请使用环境变量）
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://jrqwtcvidotzsscootjg.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpycXd0Y3ZpZG90enNzY29vdGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5OTM2NzYsImV4cCI6MjA4NzU2OTY3Nn0.zOuoeczuOCyLcLEf3QFpaIZUYhlFPi3B2YJCkAFPOtU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // 确保 headers 中包含 apikey 和 Authorization
  global: {
    headers: {
      'apikey': SUPABASE_PUBLISHABLE_KEY,
      'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
    },
  },
});