import { useParams } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { getResellerDemoState } from "@/lib/resellerDemo";
import AdminUsers from "./AdminUsers";
import AdminEnterprises from "./AdminEnterprises";

const money = (value = 0) => `¥${value.toLocaleString("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function AdminResellerPortal({ section }: { section: "users" | "enterprises" | "funds" | "bills" | "logs" }) {
  const { id = "agent-001" } = useParams();
  const state = getResellerDemoState();
  const reseller = state.resellers.find((item) => item.id === id);
  if (!reseller) return <div className="p-6 text-center text-muted-foreground">代理商不存在</div>;
  const users = state.users.filter((item) => item.resellerId === id);
  const ledger = state.ledger.filter((item) => item.resellerId === id);
  const cashLedger = ledger.filter((item) => item.type !== "commission");
  const bills = state.bills.filter((item) => item.resellerId === id);
  const title = { users: "用户管理", enterprises: "企业管理", funds: "资金账户", bills: "账单管理", logs: "调用日志" }[section];

  return <div className="p-6 space-y-5">
    <div className="flex items-center justify-between"><div className="flex items-center gap-2"><h1 className="text-xl font-semibold">{title}</h1><Badge variant="outline">代理商视图</Badge></div><p className="text-sm text-muted-foreground">{reseller.name} · {reseller.domain}</p></div>
    {section === "users" && <div className="-mx-6"><AdminUsers resellerScopeId={id} /></div>}
    {section === "enterprises" && <div className="-mx-6"><AdminEnterprises resellerScopeId={id} /></div>}
    {section === "funds" && <><div className="grid grid-cols-3 gap-4"><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">充值余额</p><p className="text-2xl font-semibold mt-2">{money(reseller.balance)}</p></div><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">授信余额</p><p className="text-2xl font-semibold mt-2">{money(reseller.creditBalance)}</p></div><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">已分配给客户</p><p className="text-2xl font-semibold mt-2">{money(reseller.totalCustomerRecharge)}</p></div></div><div className="rounded-xl border bg-card overflow-hidden"><div className="px-4 py-3 border-b font-medium">资金流水</div><div className="grid grid-cols-[180px_130px_1fr_130px_130px_130px] gap-3 px-4 py-3 border-b bg-muted/30 text-xs text-muted-foreground"><span>时间</span><span>变动类型</span><span>对象 / 备注</span><span>变动金额</span><span>变动前余额</span><span>变动后余额</span></div>{cashLedger.map((item) => <div key={item.id} className="grid grid-cols-[180px_130px_1fr_130px_130px_130px] gap-3 px-4 py-3 border-b last:border-0 text-sm items-center"><span>{new Date(item.createdAt).toLocaleString("zh-CN", { hour12: false })}</span><span>{item.type === "customer_recharge" ? "客户划拨" : item.type === "credit_adjustment" ? "授信调整" : item.type === "adjustment" ? "后台调额" : "后台充值"}</span><span>{item.targetName ? `${item.targetName} · ${item.remark}` : item.remark}</span><span className={`font-medium tabular-nums ${item.amount >= 0 ? "text-green-600" : "text-orange-600"}`}>{item.amount >= 0 ? "+" : "-"}{money(Math.abs(item.amount))}</span><span className="tabular-nums">{money(item.balanceBefore)}</span><span className="tabular-nums font-medium">{money(item.balanceAfter)}</span></div>)}{cashLedger.length === 0 && <div className="py-12 text-center text-sm text-muted-foreground">暂无资金流水</div>}</div></>}
    {section === "bills" && <div className="rounded-xl border bg-card overflow-hidden"><div className="px-4 py-3 border-b font-medium">名下客户账单</div><div className="grid grid-cols-[150px_90px_1fr_90px_120px_90px_120px_120px_100px] gap-3 px-4 py-3 bg-muted/30 border-b text-xs text-muted-foreground"><span>账单号</span><span>账期</span><span>账单主体</span><span>主体类型</span><span>原始金额</span><span>结算折扣</span><span>结算金额</span><span>实际消耗</span><span>状态</span></div>{bills.map((item) => <div key={item.id} className="grid grid-cols-[150px_90px_1fr_90px_120px_90px_120px_120px_100px] gap-3 px-4 py-3 border-b last:border-0 text-sm items-center"><span className="font-mono text-xs">{item.id}</span><span>{item.period}</span><span className="min-w-0"><span className="block truncate font-medium">{item.customerName}</span><span className="block truncate text-xs text-muted-foreground">{item.customerId}</span></span><span>{item.customerType === "enterprise" ? "企业" : "用户"}</span><span className="tabular-nums">{money(item.originalAmount)}</span><span>{Math.round(item.discount * 100)}%</span><span className="tabular-nums">{money(item.settlementAmount)}</span><span className="tabular-nums">{money(item.actualConsumed)}</span><Badge variant={item.status === "pending" ? "secondary" : "outline"} className="w-fit">{item.status === "paid" ? "已结算" : "待结算"}</Badge></div>)}{bills.length === 0 && <div className="py-12 text-center text-sm text-muted-foreground">暂无客户账单</div>}</div>}
    {section === "logs" && <div className="rounded-xl border bg-card overflow-hidden"><div className="px-4 py-3 border-b font-medium">当前代理商调用日志</div><div className="grid grid-cols-[180px_1fr_140px_120px] gap-3 px-4 py-3 bg-muted/30 border-b text-xs text-muted-foreground"><span>时间</span><span>客户 / 模型</span><span>Token 消耗</span><span>状态</span></div>{users.slice(0, 4).map((user, index) => <div key={user.phone} className="grid grid-cols-[180px_1fr_140px_120px] gap-3 px-4 py-3 border-b last:border-0 text-sm"><span>2026/8/{16 - index} 14:2{index}:18</span><span>{user.name} · MiniMax-M3</span><span>{(12840 + index * 2350).toLocaleString()}</span><Badge variant="outline" className="w-fit">成功</Badge></div>)}</div>}
  </div>;
}
